# Generated by Django 4.0 on 2021-12-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='Tasklist',
        ),
    ]
